# Generated by Django 4.2.29 on 2026-03-24 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "project_id",
                    models.UUIDField(
                        help_text="Plane project UUID (references plane.db.models.Project)",
                        unique=True,
                    ),
                ),
                ("lazy_bird_project_id", models.UUIDField(help_text="Lazy-Bird project UUID")),
                ("enabled", models.BooleanField(default=False)),
                (
                    "ready_state_name",
                    models.CharField(
                        default="Ready",
                        help_text="Plane state name that triggers task queuing",
                        max_length=100,
                    ),
                ),
                ("in_progress_state_name", models.CharField(default="In Progress", max_length=100)),
                ("review_state_name", models.CharField(default="In Review", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Automation Config",
                "verbose_name_plural": "Automation Configs",
                "db_table": "plane_lazy_bird_automation_config",
            },
        ),
        migrations.CreateModel(
            name="TaskRunMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "issue_id",
                    models.UUIDField(
                        help_text="Plane issue UUID (references plane.db.models.Issue)"
                    ),
                ),
                ("project_id", models.UUIDField(help_text="Plane project UUID")),
                ("task_run_id", models.UUIDField(help_text="Lazy-Bird task run UUID")),
                (
                    "status",
                    models.CharField(
                        default="queued",
                        help_text="Mirrored status from Lazy-Bird (queued, running, success, failed, cancelled, timeout)",
                        max_length=50,
                    ),
                ),
                ("pr_url", models.URLField(blank=True, default="")),
                ("pr_number", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Run Mapping",
                "verbose_name_plural": "Task Run Mappings",
                "db_table": "plane_lazy_bird_task_run_mapping",
                "indexes": [
                    models.Index(fields=["issue_id"], name="plane_lazy__issue_i_b5dd50_idx"),
                    models.Index(fields=["task_run_id"], name="plane_lazy__task_ru_3b9bc6_idx"),
                    models.Index(
                        fields=["project_id", "status"], name="plane_lazy__project_c7465a_idx"
                    ),
                ],
            },
        ),
    ]
