# Generated by Django 6.0.3 on 2026-03-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_lazy_bird", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationconfig",
            name="api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Per-project API key (overrides LAZY_BIRD_API_KEY env var when set)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="automationconfig",
            name="api_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Per-project Lazy-Bird API URL (overrides LAZY_BIRD_API_URL env var when set)",
            ),
        ),
    ]
